/**
 * `<source>` pair for a background video: WebM first (smaller), MP4 fallback for
 * browsers without WebM support (older Safari / iOS). Pass the .mp4 path; the
 * .webm is expected beside it (generated by `npm run optimize:assets`).
 * If the .webm is missing the browser skips to the next source.
 */
export function VideoSources({ src, media }: { src: string; media?: string }) {
  return (
    <>
      <source src={src.replace(/\.mp4$/i, ".webm")} type="video/webm" media={media} />
      <source src={src} type="video/mp4" media={media} />
    </>
  );
}
